PREFIX schema: <http://schema.org/>
PREFIX rel: <http://purl.org/vocab/relationship#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix sdo: <https://schema.org/>

SELECT * WHERE {
  #  FaSiSo
  ?child1 rel:childOf ?parent1 ;
          sdo:gender sdo:Male ;
          rdfs:label ?husband ;
          rel:spouseOf ?child2 .
  ?child2 rel:childOf ?father2 ;
          rdfs:label ?wife .
  ?father2 rel:spouseOf ?mother2 .
  ?parent1 rel:childOf ?grandparent .
  ?mother2 rel:childOf ?grandparent .
  optional{?grandchild rel:childOf ?child1 ;
                       rdfs:label ?child
  } optional{
    ?grandparent rdfs:label ?grandparent_id
  } .
} 